// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbxkIBNEi81KGPyZGd-XAQ4NeFFJJ115U',
    appId: '1:99059907848:web:3d37fa0733b36d18f400bd',
    messagingSenderId: '99059907848',
    projectId: 'holod3x',
    authDomain: 'holod3x.firebaseapp.com',
    databaseURL: 'https://holod3x-default-rtdb.firebaseio.com',
    storageBucket: 'holod3x.appspot.com',
    measurementId: 'G-PDTWGE8XF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdbps-8c_dPvgLLNXO45m2IEU3ZLfX_jQ',
    appId: '1:99059907848:android:8f50ba69b72c83c3f400bd',
    messagingSenderId: '99059907848',
    projectId: 'holod3x',
    databaseURL: 'https://holod3x-default-rtdb.firebaseio.com',
    storageBucket: 'holod3x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAID0xcavb7OwLL8_x319vnWjFZg0L2QZ4',
    appId: '1:99059907848:ios:211847fda5a0e355f400bd',
    messagingSenderId: '99059907848',
    projectId: 'holod3x',
    databaseURL: 'https://holod3x-default-rtdb.firebaseio.com',
    storageBucket: 'holod3x.appspot.com',
    iosBundleId: 'com.example.flowcraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAID0xcavb7OwLL8_x319vnWjFZg0L2QZ4',
    appId: '1:99059907848:ios:211847fda5a0e355f400bd',
    messagingSenderId: '99059907848',
    projectId: 'holod3x',
    databaseURL: 'https://holod3x-default-rtdb.firebaseio.com',
    storageBucket: 'holod3x.appspot.com',
    iosBundleId: 'com.example.flowcraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOWIcHPjT7w7KGAzXeREmLOeyL9YMmnWI',
    appId: '1:99059907848:web:48d01bd64dd739e3f400bd',
    messagingSenderId: '99059907848',
    projectId: 'holod3x',
    authDomain: 'holod3x.firebaseapp.com',
    databaseURL: 'https://holod3x-default-rtdb.firebaseio.com',
    storageBucket: 'holod3x.appspot.com',
    measurementId: 'G-DXMNNKMK3N',
  );
}
